spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hr?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=true
    username: root
    password: roleplay123

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl

